<?php
    $_helper = $this->helper('catalog/output');
    $_customHelper = $this->helper('weltpixel_custom');
    $_selectorHelper = $this->helper('weltpixel_selector');
    $ajaxAddToCartEnabled = $_selectorHelper->getAjaxAddtoCart();
    $ajaxConfirmationHide = $_selectorHelper->getAjaxAddtoCartConfirmationHide();
    $_product = $this->getProduct();
    $_productId = $_product->getId();
    $_productName = $_helper->productAttribute($_product, $_product->getName(), 'name');
    $_productSku = $_helper->productAttribute($_product, $_product->getSku(), 'sku');
    $_productShortDescription = $_helper->productAttribute($_product, nl2br($_product->getShortDescription()), 'short_description');
    $_productPrice = $this->getPriceHtml($_product, true);
    $_productReviews = $this->getReviewsSummaryHtml($_product, false, true);
    $_upsells = trim($this->getChildHtml('upsell_products'));
    $_relatedRight = trim($this->getChildHtml('related_right'));
    $_messages = trim($this->getMessagesBlock()->getGroupedHtml());
    $_review_form = $this->getChildHtml('review_form');
    $_reviews = $this->getChildHtml('reviews');
    $_settings = Mage::getStoreConfig('weltpixel_selector/productpageoptions');
    $_infoFormat = $_settings['product_info_format'] ? $_settings['product_info_format'] : "accordion";
    $_infoLayout = $_settings['product_info_layout'] ? $_settings['product_info_layout'] : "twocolumns";
    $_secondaryColumnLocation = $_settings['secondary_column_location'];
    $_imageColumnWidth = $_settings['image_column_width'];
    $_productInfoWidth = $_settings['product_info_width'];
    $_secondaryColumnWidth = $_settings['secondary_column_width'];
    $_relatedProductsCount = count($_product->getRelatedProductIds());
    $_secondaryColumnOption = $_settings['secondary_column_options']; //related,cms,replace
    $appTabsEnabled = '';
    if ($ajaxAddToCartEnabled) :
        $_productAction = $this->getSubmitUrl($_product, array());
    else :
        $_productAction = $this->getSubmitUrl($_product, array(), false);
    endif;

    $superAttributes = [];
    if ($_product->getTypeId() == 'configurable') {
        $attributes = $_product->getTypeInstance()->getConfigurableAttributes($_product);
        foreach ($attributes as $attr) {
            $superAttributes[] = $attr->getAttributeId();
        }
    }
    $superAttributes = implode(',', $superAttributes);
?>

<script>var optionsPrice = new Product.OptionsPrice(<?php echo $this->getJsonConfig(); ?>);</script>

<?php if ($_messages): ?>
    <div id="messages_product_view"><?php echo $_messages; ?></div>
<?php endif; ?>
<style>
    img.product-image {
        height: 300px;
    }
</style>
<!-- removed product view -->

<div class="targetrule-container col-xs-12">
    <div class="target-related">
        <div class="w">
            <?php echo $this->getChildHtml('related_products') ?>
        </div>
    </div>
    <div class="w">
        <?php echo $this->getChildHtml('upsell_products_enterprise') ?>
    </div>
</div>

<script>
    jQuery(function($) {
        $('.accordion').on('click', 'dt', function() {
            $('#todo').find('dt').removeClass('active');
            $('#todo').find('dd').removeClass('active');
            $(this).addClass('active');
            $(this).next('dd').addClass('active');
        });
        $('#qty').niceSelect();
        $('.super-attribute-select').niceSelect();
    });
</script>
