<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2018 Amasty (https://www.amasty.com)
 * @package Amasty_Xnotif
 */
if ($this->getType() == 'amxnotif/category_subscribe') {
    $productId = $this->getData('product')->getId();
} else {
    $productId = Mage::registry('current_product')->getId();
    $parentId = $this->getParentProductId();
}
$hideFeature = true;
?>
<p class="<?php echo $this->getHtmlClass() ?>">
    <?php if(!$hideFeature):?>
        <style>
            .oos-text{
                display: flex;
                position: absolute;
                top: 0;
                left: 0;
            }
            .oos-text span{
                color: #98b3ba;
                font-weight: 500;
                font-size: 1.5rem;
                text-transform: uppercase;
            }
        </style>
        <div class="oos-text">
            <span>Out of Stock</span>
        </div>
        
    <?php else: ?>
        <a href="<?php echo $this->escapeHtml(Mage::helper('amxnotif')->getSignupUrl('stock', $productId, $parentId)) ?>" >
            <?php echo $this->escapeHtml($this->__($this->getSignupLabel())); ?>
        </a>
    <?php endif; ?>
    
</p>
